### ISSUE TITLE
遥远的时空中~八叶抄

### ISSUE THREAD

**Issue by sum2012** [sum2012/ppsspp-problem#49]
@tpunix 
請提供遊戲iso ,謝謝

**Comment by tpunix** [comment]
链接:http://pan.baidu.com/s/1qY266RU 密码:46zv
这是汉化iso, 暂时不要外传 

在2016年04月29 03时41分, "sum"notifications@github.com写道:

@tpunix
請提供遊戲iso ,謝謝

**Comment by tpunix** [comment]
加个qq吧: 7605781
