### ISSUE TITLE
UFC Undisputed 2010 - black screen after Intro

### ISSUE THREAD

**Issue by sum2012** [sum2012/ppsspp-problem#50]
@paplo2k16  
try only use non-rip

**Comment by paplo2k16** [comment]
@sum2012  

Thanks alot man, its the iso problem then it worked, damn csos, is mgs pw working too and thanx again man, ur awesome.

![solvd1](https://cloud.githubusercontent.com/assets/19208362/15095993/7d517170-1502-11e6-9f81-3af54f9e6417.png)

**Comment by sum2012** [comment]
1

**Comment by paplo2k16** [comment]
@sum2012  afer downloading ur iso I deleted the files, but I downloaded the files from here only-

http://rugame.mobi/android/22456/2/384c7f59604fc67b96a08edca8e8779d1d/UFC20105xxRIP.rar

http://rugame.mobi/android/22455/

**Comment by sum2012** [comment]
Yes,ppsspp don't work but real psp work
