### ISSUE TITLE
Rewrite VN: compatibility issues and crashes 

### ISSUE THREAD

**Issue by sum2012** [sum2012/ppsspp-problem#56]
@4vate How to play in real psp without real card ?

**Comment by ghost** [comment]
I'm pretty sure you need a memory card for it to run.
- Insert DISC1, install it, that creates a savefile ULJM06364INSTALL (game data, 413MBs in size)
- When prompted to switch disc, do so. On PPSSPP, the *Switch UMD* option doesn't work but is not required. Just stopping emulation and launching DISC2 is fine.
- On DISC2, the game asks you to remove the memory card, press circle, remove the memstick, press circle, put the memstick back
- This action creates a [ULJM06364SYSTEM](https://github.com/sum2012/ppsspp-problem/files/9433408/ULJM06364SYSTEM.zip) save, which consists of user settings and a skip for the memory card removal for the next launch of the game.

**Comment by sum2012** [comment]
I mean need money to buy PSP games.
Like this picture https://www.carousell.com.hk/p/psp-game-1170427815/?t-id=OYPtz4tpJf_1661520493094&t-referrer_browse_type=search_results&t-referrer_context=category_slp&t-referrer_request_id=VkzHngiC0CdeX3n0&t-referrer_search_query=psp%20game&t-referrer_source=search_landing&t-tap_index=6

I have real psp,I try to run into it.(I have downloaded the two isos)
![1661520674423](https://user-images.githubusercontent.com/2177532/186915496-226dc29e-e168-4b34-abab-f8cf794f3b98.jpg)

**Comment by sum2012** [comment]
The picture is large,you may easier to see in 
https://ibb.co/JdNXp4D

**Comment by ghost** [comment]
Are you running CFW? You need the two .iso's in the ISO folder on your memory card and the console should just regulary boot them, then follow the instructions I listed above.
After installing the DISC1 just quit game and boot DISC2, you dont need any seplugins allowing isoswap

**Comment by sum2012** [comment]
Thanks.NowI know how to physically to remove the memory card
